config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
 validates :name, presence: true
 validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

 def home

 end

 def about

 end

 def help

 end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

 before_action :set_todo, only: [:show, :edit, :update, :destroy]

 def new
   @todo = Todo.new
 end

 def create

   @todo = Todo.new(todo_params)

   if @todo.save
    flash[:notice] = "ToDo zostało stworzone poprawnie"
    redirect_to todo_path(@todo)
   else
    render 'new'
   end
 end

 def show
   
 end

 def edit
   
 end

 def update
   
   if @todo.update(todo_params)
     flash[:notice] = "Todo poprawione zostało zapisane"
     redirect_to todo_path(@todo)
   else
     render 'edit'
   end
 end

 def index
  @todos = Todo.all
 end

 def destroy
  @todo.destroy
  flash[:notice] = "ToDo zostało poprawnie usunięte."
  redirect_to todos_path
 end

 private

 def todo_params
   params.require(:todo).permit(:name, :description)
 end

 def set_todo
  @todo = Todo.find(params[:id])
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li> <%= msg %> </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> About page </h1>

app/views/pages/help.html.erb
<h1> Help page </h1>

app/views/pages/home.html.erb
<h1> Hello World </h1>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <h2> Błędy w formularzu </h2>
  <ul>
    <% @todo.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @todo do |f| %>
<p>
  <%= f.label :name %> </br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :description %> </br>
  <%= f.text_area :description %> </br>
</p>
<p>
  <%= f.submit "Zapisz" %>
</p>
<% end %>

<%= link_to "Domowa", todos_path %>

app/views/todos/edit.html.erb
<h1> Edit ToDo </h1>

<%= render 'form' %>

app/views/todos/index.html.erb
<h1> Wszystkie ToDo </h1>

<p>
	<%= link_to "Stwórz ToDo", new_todo_path %>
</p>
<table>
	
	<tr>
		<th>
			Name
		</th>
		<th>
			Description
		</th>
	</tr>
	<% @todos.each do |todo| %>
		<tr>
			<td>
				<%= todo.name  %>
			</td>
			<td>
				<%= todo.description %>
			</td>
			<td>
				<%= link_to "Edycja", edit_todo_path(todo) %>
			</td>
			<td>
				<%= link_to "Pokaż", todo_path(todo) %>
			</td>
			<td>
				<%= link_to "Usuń", todo_path(todo), method: :delete, data: {confirm: "Czy jesteś pewien ?"} %>
			</td>
		</tr>
	<% end %>
</table>

app/views/todos/new.html.erb
<h1> Create new ToDo </h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1> Pokazanie ToDo </h1>

<p>
  id: <%= @todo.id %>
</p>
<p>
  name: <%= @todo.name %>
</p>
<p>
  description: <%= @todo.description %>
</p>

<p>
	<%= link_to "Domowa", todos_path %> 
	<%= link_to "Edycja", edit_todo_path(@todo) %>
</p>